# Generated by Django 4.0.4 on 2022-06-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='Date sent')),
            ],
        ),
    ]
