# Generated by Django 4.0.4 on 2022-06-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_alter_sms_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='sms_id',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='sms',
            name='date',
            field=models.DateTimeField(verbose_name='date sent'),
        ),
    ]
