# Generated by Django 4.0.4 on 2022-06-10 23:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_sms_sms_id_alter_sms_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('sms_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
